# Demo pipeline to conduct a Veracod Dynamic Analysis Scan (create or update)

trigger:
#- master
- none

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    DAST_SCAN:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Setup Veracod Dynamic Analysis Scan'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    export Dynamic_Target=$(DYNAMIC_TARGET)
    export JOB_NAME='$(system.teamProject)_ADO_yaml_DAST'
    export VeraID=$(VERAID)
    export VeraPW=$(VERAPW)
    export Dynamic_User=$(DYNAMIC_USER)
    export Dynamic_Pass=$(DYNAMIC_PASS)
    python create-or-update-da-scan.py
  displayName: 'Create or update and run the Dynamic Analysis'
